runtime: nodejs10

manual_scaling:
  instances: 1

env_variables:
  LOG_NAME: world-sport-action/api
  LOG_LEVEL: debug
  SECRET: VTB9wKmchJT
  MYSQL_SOCKET_PATH: /cloudsql/world-sport-action:australia-southeast1:world-sport-action-dev
  MYSQL_USER: root
  MYSQL_PASSWORD: KEzHi3KpvBblh9ah
  MYSQL_DATABASE: wsa_prod
  SENDGRID_API_KEY: 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
  SERVER_URL: https://world-sport-action.appspot.com
  CheckSocket: 0
  MAIL_USERNAME: admin@worldsportaction.com
  MAIL_PASSWORD: NLSwebadm1n
  
beta_settings:
  cloud_sql_instances: world-sport-action:australia-southeast1:world-sport-action-dev
